In [1]:
import torch

a = torch.tensor([1.2, 2.3, 6.0, 7.1])
b = torch.tensor([2.0, 1.5, 3.36, 0.111])

In [2]:
# Element-wise addition
a + b

tensor([3.2000, 3.8000, 9.3600, 7.2110])

In [3]:
# Element-wise subtraction
a - b

tensor([-0.8000,  0.8000,  2.6400,  6.9890])

In [4]:
# Element-wise multiplication
a * b

tensor([ 2.4000,  3.4500, 20.1600,  0.7881])

In [5]:
# Element-wise division
a / b

tensor([ 0.6000,  1.5333,  1.7857, 63.9640])

# Sigmoid

In [6]:
torch.sigmoid(a)

tensor([0.7685, 0.9089, 0.9975, 0.9992])

In [7]:
torch.sigmoid(torch.tensor(381))

tensor(1.)

In [8]:
torch.sigmoid(torch.tensor(0))

tensor(0.5000)

In [9]:
torch.sigmoid(torch.tensor(-0.41))

tensor(0.3989)

# ReLU (Rectified Linear Unit)

In [10]:
c = torch.tensor([21, -5, 0, 7])
torch.relu(c)

tensor([21,  0,  0,  7])

# Dot Product

In [11]:
a = torch.tensor([1.0, 3.0, 5.0, 7.0])
b = torch.tensor([2.0, 0.5, 0.25, 0.75])

torch.dot(a, b)

tensor(10.)